version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - APP_ENV=production
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "5173:5173"  # Map port 5173 for Vite
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable file watching in Docker
    depends_on:
      - backend
    restart: unless-stopped